# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DisFac.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 320)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(140, 10, 151, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 40, 71, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 90, 81, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 130, 101, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(30, 170, 54, 12))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(30, 210, 54, 12))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(30, 250, 61, 16))
        self.label_7.setObjectName("label_7")
        self.big_hazards = QtWidgets.QPlainTextEdit(Dialog)
        self.big_hazards.setGeometry(QtCore.QRect(110, 40, 261, 31))
        self.big_hazards.setObjectName("big_hazards")
        self.small_hazards = QtWidgets.QPlainTextEdit(Dialog)
        self.small_hazards.setGeometry(QtCore.QRect(110, 80, 261, 31))
        self.small_hazards.setObjectName("small_hazards")
        self.diseases = QtWidgets.QPlainTextEdit(Dialog)
        self.diseases.setGeometry(QtCore.QRect(110, 120, 261, 31))
        self.diseases.setObjectName("diseases")
        self.occupations = QtWidgets.QPlainTextEdit(Dialog)
        self.occupations.setGeometry(QtCore.QRect(110, 160, 261, 31))
        self.occupations.setObjectName("occupations")
        self.examples = QtWidgets.QPlainTextEdit(Dialog)
        self.examples.setGeometry(QtCore.QRect(110, 200, 261, 31))
        self.examples.setObjectName("examples")
        self.tag = QtWidgets.QPlainTextEdit(Dialog)
        self.tag.setGeometry(QtCore.QRect(110, 240, 261, 31))
        self.tag.setObjectName("tag")
        self.addrule = QtWidgets.QPushButton(Dialog)
        self.addrule.setGeometry(QtCore.QRect(50, 290, 75, 23))
        self.addrule.setObjectName("addrule")
        self.removerule = QtWidgets.QPushButton(Dialog)
        self.removerule.setGeometry(QtCore.QRect(160, 290, 75, 23))
        self.removerule.setObjectName("removerule")
        self.clearrule = QtWidgets.QPushButton(Dialog)
        self.clearrule.setGeometry(QtCore.QRect(270, 290, 75, 23))
        self.clearrule.setObjectName("clearrule")
        self.goback = QtWidgets.QPushButton(Dialog)
        self.goback.setGeometry(QtCore.QRect(10, 10, 75, 23))
        self.goback.setObjectName("goback")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "更新职业病-有害因素关系"))
        self.label_2.setText(_translate("Dialog", "有害因素大类"))
        self.label_3.setText(_translate("Dialog", "有害因素小类"))
        self.label_4.setText(_translate("Dialog", "可能对应的职业病"))
        self.label_5.setText(_translate("Dialog", "所属行业"))
        self.label_6.setText(_translate("Dialog", "工种举例"))
        self.label_7.setText(_translate("Dialog", "职业病标签"))
        self.addrule.setText(_translate("Dialog", "增加关系"))
        self.removerule.setText(_translate("Dialog", "删除关系"))
        self.clearrule.setText(_translate("Dialog", "清空"))
        self.goback.setText(_translate("Dialog", "返回主菜单"))
