# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DisSym.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(440, 332)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(160, 10, 131, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(70, 60, 54, 12))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 100, 151, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 170, 161, 20))
        self.label_4.setObjectName("label_4")
        self.name = QtWidgets.QPlainTextEdit(Dialog)
        self.name.setGeometry(QtCore.QRect(160, 50, 251, 31))
        self.name.setObjectName("name")
        self.level = QtWidgets.QPlainTextEdit(Dialog)
        self.level.setGeometry(QtCore.QRect(160, 90, 251, 31))
        self.level.setObjectName("level")
        self.symptoms = QtWidgets.QPlainTextEdit(Dialog)
        self.symptoms.setGeometry(QtCore.QRect(160, 150, 251, 91))
        self.symptoms.setObjectName("symptoms")
        self.addrules = QtWidgets.QPushButton(Dialog)
        self.addrules.setGeometry(QtCore.QRect(70, 280, 75, 23))
        self.addrules.setObjectName("addrules")
        self.removerules = QtWidgets.QPushButton(Dialog)
        self.removerules.setGeometry(QtCore.QRect(190, 280, 75, 23))
        self.removerules.setObjectName("removerules")
        self.clearrules = QtWidgets.QPushButton(Dialog)
        self.clearrules.setGeometry(QtCore.QRect(310, 280, 75, 23))
        self.clearrules.setObjectName("clearrules")
        self.goback = QtWidgets.QPushButton(Dialog)
        self.goback.setGeometry(QtCore.QRect(10, 10, 75, 23))
        self.goback.setObjectName("goback")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "更新职业病-症状关系"))
        self.label_2.setText(_translate("Dialog", "疾病名称"))
        self.label_3.setText(_translate("Dialog", "疾病严重量级、急慢性量级"))
        self.label_4.setText(_translate("Dialog", "症状（两两之间用空格分隔）"))
        self.addrules.setText(_translate("Dialog", "增加关系"))
        self.removerules.setText(_translate("Dialog", "删除关系"))
        self.clearrules.setText(_translate("Dialog", "清空"))
        self.goback.setText(_translate("Dialog", "返回主菜单"))
